### ISSUE TITLE
Difference with Pympler?

### ISSUE THREAD

**Issue by worldmind** [fonaro/objsize#1]
Can anybody compare this module with [Pympler](https://pypi.org/project/Pympler/)?

**Comment by fonaro** [comment]
There are three main differences:

1. This module supports traversing the object sub-tree: iterating all of the object's descendants one by one.

2. This module supports excluding non-exclusive objects. I.e., objects that are also referenced from somewhere else in the program. This is true for calculating the object's deep size and for traversing its descendants.

3. This module has a simple and robust implementation with significantly fewer lines of code, as opposed to Pympler implementation.
The Pympler implementation uses recursion, and thus have to use a maximal depth argument to avoid reaching Python's max depth. This module uses BFS which is more efficient and simple to follow.
Moreover, the Pympler implementation carefully takes care of any object type. This module archives the same goal with a more generic implementation, which is simpler and has fewer lines of code.

**Comment by worldmind** [comment]
@fonaro thanks for answer, I think that such explanation must be in Readme.md

**Comment by fonaro** [comment]
That is a good point. See the update readme.

**Comment by worldmind** [comment]
Great, thanks.
